### ISSUE TITLE
Set up NTPsec server

### ISSUE THREAD

**Issue by zx96** [zx96/anlcdc2017#3]

**Comment by JasonElting** [comment]
The server has the software installed, just needs configuration.

**Comment by wolfer55** [comment]
should we use NTPsec instead of just installing NTP?  I've looked at it a little and it seems like we just set it up instead of NTP.

**Comment by JasonElting** [comment]
It is NTPsec, forgot to specify that.

**Comment by zx96** [comment]
NTPsec is an implementation of NTP.  I decided to keep the issue title generic.

**Comment by zx96** [comment]
NTP is installed and configured, with a lovely systemd service file courtesy of yours truly.  It just needs to have iptables configured now!
